version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: AuthenticationContainer
    restart: always
    environment:
      POSTGRES_DB: Authentication
      POSTGRES_USER: MyUser
      POSTGRES_PASSWORD: myPassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
